version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finx_tracker_local_django
    container_name: finx_tracker_local_django
    platform: linux/x86_64
    depends_on:
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local.aws/.django
      - ./.envs/.local.aws/.postgres
    ports:
      - "8000:8000"
    command: /start

  django-cli:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finx_tracker_local_django
    container_name: finx_tracker_local_django
    platform: linux/x86_64
    depends_on:
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local.aws/.django
      - ./.envs/.local.aws/.postgres
    ports:
      - "8000:8000"
    command: python

  redis:
    image: redis:6
    container_name: finx_tracker_local_redis

  celeryworker:
    <<: *django
    image: finx_tracker_local_celeryworker
    container_name: finx_tracker_local_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: finx_tracker_local_celerybeat
    container_name: finx_tracker_local_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: finx_tracker_local_flower
  #   container_name: finx_tracker_local_flower
  #   ports:
  #     - "5555:5555"
  #   command: /start-flower
