# Generated by Django 3.2.13 on 2022-08-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='trade',
        #     options={'managed': False},
        # ),
    ]
