# Generated by Django 3.2.13 on 2022-09-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_trade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
