# Generated by Django 3.2.13 on 2022-09-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_trade_groupings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'managed': True},
        ),
    ]
