# Generated by Django 3.2.13 on 2023-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_alter_trade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='acct_alias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exch_order_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='issuer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='order_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
