# Generated by Django 3.2.13 on 2022-05-14 15:33

from django.db import migrations, models
import finx_tracker.portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_alias', models.FloatField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=models.DO_NOTHING, to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolios_strategy',
                'managed': True,
            },
        ),
    ]
