# Generated by Django 3.2.13 on 2022-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20220519_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='name',
            field=models.CharField(default='Unnamed', max_length=50),
        ),
    ]
