# Generated by Django 3.2.13 on 2022-05-19 15:12

from django.db import migrations, models
import finx_tracker.portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20220519_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='ext_trade_id',
        ),
        migrations.CreateModel(
            name='StrategyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_trade_id', models.IntegerField(default=-1, unique=True)),
                ('grouping_id', models.IntegerField(default=-1, unique=True)),
                ('strategy', models.ForeignKey(on_delete=models.DO_NOTHING, to='portfolios.strategy')),
            ],
            options={
                'db_table': 'portfolios_strategy_trade',
                'managed': True,
            },
        ),
    ]
