# Generated by Django 3.2.13 on 2022-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20220519_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategytrade',
            name='ext_trade_id',
            field=models.BigIntegerField(default=-1, unique=True),
        ),
    ]
