# Generated by Django 3.2.13 on 2022-05-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_alter_strategytrade_ext_trade_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategytrade',
            name='grouping_id',
        ),
        migrations.AddField(
            model_name='strategytrade',
            name='group_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
