# Generated by Django 3.2.13 on 2022-08-21 15:03

from django.db import migrations, models
import finx_tracker.portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytrade',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=finx_tracker.portfolios.models.on_delete_callable, to='portfolios.group'),
        ),
    ]
