# Generated by Django 3.2.13 on 2022-08-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_strategytrade_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategytrade',
            name='group_name',
        ),
    ]
