# Generated by Django 3.2.13 on 2022-08-21 20:31

from django.db import migrations, models
import finx_tracker.portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_remove_strategytrade_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.DO_NOTHING, to='portfolios.strategy'),
        ),
    ]
