# Generated by Django 3.2.13 on 2022-08-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_group_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategytrade',
            name='strategy',
        ),
    ]
