# Generated by Django 3.2.13 on 2022-08-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_remove_strategytrade_strategy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Grouping',
        ),
        migrations.RenameModel(
            old_name='StrategyTrade',
            new_name='GroupingTrade',
        ),
        migrations.AlterModelTable(
            name='grouping',
            table='portfolios_grouping',
        ),
        migrations.AlterModelTable(
            name='groupingtrade',
            table='portfolios_grouping_trade',
        ),
    ]
