# Generated by Django 3.2.13 on 2022-08-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='acct_alias',
            new_name='conid',
        ),
        migrations.AddField(
            model_name='position',
            name='closing_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
