# Generated by Django 3.2.13 on 2022-08-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_alter_grouping_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='name',
            new_name='key',
        ),
    ]
