# Generated by Django 3.2.13 on 2022-09-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_trade_trade_id'),
        ('portfolios', '0018_rename_name_strategy_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupingtrade',
            name='ext_trade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.trade', to_field='trade_id'),
        ),
    ]
