# Generated by Django 3.2.13 on 2022-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0019_alter_groupingtrade_ext_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupingtrade',
            name='ext_trade_id',
            field=models.BigIntegerField(default=-1, unique=True),
        ),
    ]
