# Generated by Django 3.2.13 on 2022-09-03 19:05

from django.apps import apps
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def copy_field(app, schema):
    GroupingTrade = apps.get_model('portfolios', 'GroupingTrade')
    GroupingTrade.objects.all().update(trade_id=F('ext_trade_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_trade_trade_id'),
        ('portfolios', '0021_auto_20220903_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupingtrade',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trades.trade', to_field='trade_id'),
            preserve_default=False,
        ),

        migrations.RunPython(copy_field),
    ]
