# Generated by Django 3.2.13 on 2022-09-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0022_auto_20220903_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupingtrade',
            name='ext_trade_id',
        ),
    ]
