# Generated by Django 3.2.13 on 2022-09-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0024_grouping_trades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='finx_account_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
